### ISSUE TITLE
Francesca's French Bakery

### ISSUE THREAD

**Issue by laihugaode** [Felhaba/Everyday-Excel-Part-3#1]
Hi，i'm a excel leaner from coursera
when I finish my Francesca's French Bakery assignment and click the GRADE button
but  when it comes to the last procedure
it always says
"Not quite, it doesn't look like the newly added recipe ingredients arebeing incorporated into the Dashboard correctly. Try again!"
I work on this issue for two hours but still can't find what's wrong
can you help me?
**the attach file type xlsm can't be supportted**
### can you give me a e-mail address?
or you can send an e-mail to me
_qaz1528921961@163.com_
THANKS

**Comment by Felhaba** [comment]
Hey, thanks for reaching out. 

I'll check the file attached. I did my submissons using MacOS, wo that may be the reason why one is not supported. However, I'll check!

**PS:** I checked this file and it passes successfully. I opened it via Excel without any problems. Maybe you just need to set the default app for that type of files.

**Comment by laihugaode** [comment]
[Francesca's French Bakery - STARTER-.xlsx](https://github.com/user-attachments/files/16495715/Francesca.s.French.Bakery.-.STARTER-.xlsx)
hi，I change the file type xlsm to xlsx
maybe you should change the filename extension once download it
I look forward to receive your reply

**Comment by Felhaba** [comment]
> maybe you should change the filename extension once download it 

Well, It depends on your laptop. Anyway, after saving the file with the extension supported by your laptop, it should pass.
